# Test against this version of Node.js
# environment:
#  nodejs_version: "4.2.2"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: cd fe
  # install modules
  - npm install
  - gulp buld
# Post-install test scripts.

# Don't actually build.
build: off